### ISSUE TITLE
Backend: creating a Django REST backend

### ISSUE THREAD

**Issue by Xlin123** [micheals-meetballs/Meetballs#3]
It turns out Dart doesn't really have a proper backend framework that works with Flutter so we have two options.

1. Firebase (Backend as a service) 
2. A custom framework (I chose python since most of us know it) --> Django.

For this ticket all I want is a basic CRUD to a mock database.  (You can probably find a tutorial online if you search "Django CRUD to mock database")

No need for anything fancy, just make a User model with email and password. We'll figure out more later.

Anyone can pick this up, if you're more interested in backend feel free to take this as your first one 💯

**Comment by VidyaYadavv1519** [comment]
hiii, can you please assign me ??

**Comment by Xlin123** [comment]
@VidyaYadavv1519 This is a side project meant for a couple of my friends, however, if nobody picks it up soon I don't mind assigning it over to you.

**Comment by Xlin123** [comment]
@micheals-meetballs/volleyball-app if nobody wants to pick this up I'm giving it to bro
