### ISSUE TITLE
DevOp/Backend: Create a server  + database in Google Cloud Platform

### ISSUE THREAD

**Issue by Xlin123** [micheals-meetballs/Meetballs#4]
I probably need to make a gcp account for the team so who ever wants to work on this can work on this with me :)

We need 1 datastore for app data and a LDAP Cloud Server for user authentication.

Then we need to connect it to our Django backend.

**Comment by c1nunmaru** [comment]
I can help with this , but unable to assign myself to it. 
(dont know if i have perms)

**Comment by Xlin123** [comment]
@c1nunmaru try again, i think i fixed it

**Comment by c1nunmaru** [comment]
> [@c1nunmaru](https://github.com/c1nunmaru) try again, i think i fixed it

still the same not able to assign myself

**Comment by Xlin123** [comment]
moving to azure
